### PR TITLE
Use logical operators for bool converions.

### PR DESCRIPTION
**Pull request by rtakacs**
The explicit boolean type conversion (introduced by #2575) desn't work
with TizenRT if custom boolean representation is used. Of course,
TizenRT gives an opportunity to use the C99 standard boolean (that works
well if that is set).

I've replaced all the explicit boolean type conversions with double
negations that helps to work JerryScript well with custom boolean types.

(Note: this patch fixes 14 tests on TizenRT.)

### CODE REVIEW

**Comment by akosthekiss** [comment]
@rtakacs What is the compilation error message on TizenRT? What type of `x` can cause `(bool) x` to fail but `!!x` to pass??

**Comment by zherczeg** [comment]
As far as I understand TizenRT has a built-in "bool emulation" layer for whatever reason. In this layer bool is defined as uint8_t, and (bool)(a & b) is the last 8 bit of the result operation. Obviously this is not the same as the logical value of (a & b).

**Comment by akosthekiss** [comment]
@zherczeg Yikes! Thanks for the background.

**Comment by rtakacs** [comment]
@akosthekiss There is no compilation error message. The explicit conversation has runtime side effect that appears on some tests.

File: jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c [hunk 1]
```diff
@@ -650,7 +650,7 @@ ecma_builtin_number_prototype_object_to_fixed (ecma_value_t this_arg, /**< this
                                                                    num_digits + 1,
                                                                    exponent + frac_digits,
                                                                    &exponent,
-                                                                   ecma_number_is_zero (this_num));
+                                                                   !!ecma_number_is_zero (this_num));
```
[the remark this answers is not in the document]
Comment (rtakacs) [reply jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c]: You are right, that's indeed unnecessary change.

**Comment by zherczeg** [comment]
(I like `!= 0` more than `!!` although not a strict requirement)

Btw the TizenRT implementation:
https://github.com/Samsung/TizenRT/blob/master/os/include/stdbool.h

**Comment by akosthekiss** [comment]
I kind of tend to agree with @zherczeg. `!= 0` is something we use throughout the code base, but I cannot recall to have seen `!!` in JerryScript before. (I'll double check in some minutes.)

**Comment by akosthekiss** [comment]
- `!!` is only used in the definitions of `JERRY_LIKELY`, `JERRY_UNLIKELY`, and `JERRY_STATIC_ASSERT_GLUE`; and at a single assertion in `jerry_debugger_receive`.
- `bool.*!= 0` is used 3 times in "real" code, always in scenarios like `& CBC_CODE_FLAGS_STRICT_MODE) != 0`

I think we should follow the existing pattern (`!= 0`).

PS: Self revision, however: 3 times is not "throughout the code base".

**Comment by LaszloLango** [comment]
@akosthekiss `!!` is used in the current code base in a few place (JERRY_STATIC_ASSERT, JERRY_LiKELY, JERRY_UNLIKELY, etc.). I don't have strong preferences, `!!` and `!=0` are both good to me, although `!!` is shorter so it is a bit better to my eyes.

**Comment by rtakacs** [comment]
@LaszloLango @akosthekiss @zherczeg Thank you for your opinion. I've changed `!!` to `!= 0`.
